name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
      - name: Build with Maven
        run: mvn clean package
      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: library-jar
          path: target/city-rail-system-1.0-SNAPSHOT.jar
